// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.21'
    }
}

allprojects {
    repositories {
        // This legacy artifact was published only to JCenter.
        exclusiveContent {
            forRepository {
                maven { url = uri("https://maven.aliyun.com/repository/jcenter") }
            }
            filter { includeModule("org.zakariya.stickyheaders", "stickyheaders") }
        }
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
